feedback/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'feedback'

urlpatterns = [
    path('', views.feedback, name='feedback'),
    url(r'feedback/(?P<pk>[0-9]+)/delete/$',
        views.feedback_delete.as_view(), name='feedback_delete')
]

kalori/urls.py
from django.contrib import admin
from django.urls import path
from .views import index,get_kalori
urlpatterns = [
    path('', index,name="index_kalori"),
    path('getkalori/',get_kalori,name="get_kalori")
]

ppw_tk2/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from history.views import homepage,signup,login,logout
from kalori.views import food_index,getFood
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',homepage,name='homepage'),
    path('pemesanan/',include('pemesanan.urls')),
    path('history/', include('history.urls')),
    path('feedback/',include('feedback.urls')),
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('kalori/',include('kalori.urls')),
    path('logout/',logout, name='logout'),
    
    #path('news/',news_index,name="news"),
    #path('news/get-news/',getNews,name='get-news'),
    path('search/',food_index,name="searchFood"),
    path('search/get-food/',getFood,name='get-food')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/models.py
from django.db import models


class SavedFeedback(models.Model):
    feedback = models.CharField(max_length=300)
    testimony = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add=True)

feedback/forms.py
from django import forms
from feedback import models


class FeedbackForm(forms.Form):
    feedback = forms.CharField(
        label='Your Feedback : ',
        required=True,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'type': 'text',
            'placeholder': "Give your feedback here! ^.^"})
    )
    testimony = forms.CharField(
        label='What\'s your thought about this website?',
        required=True,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'type': 'text',
            'placeholder': "Share your testimony here! ^.^"})
    )


class Meta:
    model = models.SavedFeedback
    fields = ('feedback', 'testimony')

feedback/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from .models import SavedFeedback
from .forms import FeedbackForm

from django.http import (
    HttpResponseNotAllowed, HttpResponseRedirect,
    HttpResponseForbidden, HttpResponseNotFound,
)
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate, logout


class feedback_delete(DeleteView):
    model = SavedFeedback
    success_url = reverse_lazy('feedback:feedback')


def feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)

        if 'id' in request.POST:
            SavedFeedback.objects.get(id=request.POST['id']).delete()
            return redirect('/')

        if form.is_valid():
            # feedback = request.POST['feedback']
            feedback = SavedFeedback(
                feedback=form.data['feedback'],
                testimony=form.data['testimony']
            )
            feedback.save()
            return redirect('/')

    else:
        form = FeedbackForm()

    feedback_content = {'events': SavedFeedback.objects.all().values(),
                        'form': form}
    return render(request, 'feedback.html', feedback_content)

feedback/templates/feedback.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'sikantin.css' %}">
    <title>Feedback Kamu!</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark" id="nav">
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}" style=" color: rgb(80, 80, 80);"><b>Logout</b></a>
        {% else %}
        <p></p>
        {% endif %}
    </nav>

    <section class="half container-fluid flex-column flex-lg-row m-auto w-50">
        <br>
        <h2 style="text-align: center">Halo {{ user.username }}, Beri Feedback & Testimony-mu ^.^ !!</h2>
        <br>
        <div class="schedule col-sm h-100 d-flex justify-content-center align-items-center">
            <form method="POST">
                {% csrf_token %}
                {% for field in form %}
                <p class="w-100 justify-content-center my-1">{{ field.label }} <br> {{ field }}</p>
                {% endfor %}
                <button id="submit" type="submit" value="Submit" class="btn btn-dark mx-auto mt-2"
                    style="float: right;">Kirim</button>
            </form>
        </div>
        <br>
    </section>

    <section class="schedule w-100 d-flex flex-column flex-lg-row justify-content-center align-items-center"
        id="body-dark">
        <div class="row m-auto w-50" style="overflow: hidden; overflow-y:auto; height: 70%;" id="bg-down">
            {% for i in events %}
            <div>
                <h5 style="padding-left: 15px">Feedback {{ user.username }} :</h5>
            </div>
            <div class="container">
                <div class="text-monospace">
                    <p>{{ i.feedback }}</p>
                    <p style="float: right;">{{ i.date }}</p>
                </div>
            </div>

            <div class="col-sm-12 d-flex align-items-end justify-content-end" style="padding-right: 35px">
                <form method="POST" action="{% url 'feedback:feedback_delete' i.id %}">
                    {% csrf_token %}
                    <input name="id" value="{{i.id}}" type="hidden">
                    <button id="delete" type="" class="btn btn-outline-dark btn-sm"
                        style="margin-left: 30%; font-size: 0.8rem;">Delete</button>
                </form>
            </div>
            {% endfor %}
        </div>
    </section>
</body>

</html>