kalori/urls.py
from django.contrib import admin
from django.urls import path
from .views import index,get_kalori
urlpatterns = [
    path('', index,name="index_kalori"),
    path('getkalori/',get_kalori,name="get_kalori")
]

ppw_tk2/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from history.views import homepage,signup,login,logout
from kalori.views import food_index,getFood
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',homepage,name='homepage'),
    path('pemesanan/',include('pemesanan.urls')),
    path('history/', include('history.urls')),
    path('feedback/',include('feedback.urls')),
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('kalori/',include('kalori.urls')),
    path('logout/',logout, name='logout'),
    
    #path('news/',news_index,name="news"),
    #path('news/get-news/',getNews,name='get-news'),
    path('search/',food_index,name="searchFood"),
    path('search/get-food/',getFood,name='get-food')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kalori/models.py
from django.db import models

# Create your models here.
class Calorie(models.Model):
    total_calories=models.PositiveIntegerField(default=1,blank=True,null=True)
    class Meta:
        verbose_name_plural = "total_calories"

kalori/forms.py
from django import forms
class CalorieForm(forms.Form):
    ACTIVITY=(
        ('Tidak Terlalu Aktif','Tidak Terlalu Aktif'),('Lumayan Aktif','Lumayan Aktif'),('Sangat Aktif','Sangat Aktif')
    )
    GENDER=(
        ('Pria','Pria'),('Wanita','Wanita')
    )
    AGE=(
        ('Remaja','Remaja'),('Dewasa','Dewasa'),('Lansia','Lansia')
    )
    age=forms.ChoiceField(choices=AGE,required=False,label="Jenjang Umur")
    gender=forms.ChoiceField(choices=GENDER,required=False,label="Jenis Kelamin")
    activity=forms.ChoiceField(choices=ACTIVITY,required=False,label="Frekuensi Aktivitas")

class SearchFoodForm(forms.Form):
    attrs1 = {
        'type':'query',
        'class': 'form-control',
        'id':'search1-query',
        'placeholder':'Masukkan nama makanan di sini'
    }
    attrs2 = {
        'type':'query',
        'class': 'form-control',
        'id':'search2-query',
        'placeholder':'Masukkan kalori minimum di sini'
    }
    keyFood = forms.CharField(required=False,label='Nama Makanan', widget=forms.TextInput(attrs=attrs1))
    keyCalorie=forms.CharField(required=False,label='Kalori Minimum', widget=forms.TextInput(attrs=attrs2))

kalori/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse,JsonResponse
# Create your views here.
from django.contrib.auth.decorators import login_required
from pemesanan.models import Order,OrderCounter,Orderedfood
from .forms import CalorieForm,SearchFoodForm
from .models import Calorie
import requests
import json
from django.conf import settings


def food_index(request):
    form=SearchFoodForm()
    return render(request,'searchFood.html',{'form':form,'user':request.user})

def getFood(request):
    response = {}
    responseCode = 0
    food=request.GET.get('query',None)
    cal=request.GET.get('cal',None)
    #key=settings.FOODAPI_KEY
    key='8313377d94024b0ab5a1b39dad727e5a'
    url = 'https://api.spoonacular.com/recipes/complexSearch?query={}&minCalories={}&apiKey={}'.format(food,cal,key)
    
    return JsonResponse(requests.get(url).json())



@login_required
def index(request):
    response={'form':CalorieForm}
    counter=OrderCounter.objects.get(pk=1)
    counterVal=counter.counter-1
    order=Order.objects.get(order_id=counterVal)
    ans=0
    try:
        out=order.orderedfood_set.all()
    except:
        return redirect("homepage")
    for item in out:
        ans+=(item.attr.calories*item.amount)
    try:
        calorie=Calorie.objects.get(pk=1)
    except Calorie.DoesNotExist:
        calorie=Calorie(total_calories=0)
        calorie.save()
    finally:
        calorie=Calorie.objects.get(pk=1)
        calorie.total_calories=ans
        calorie.save()
    return render(request,'kalori.html',response)

@login_required
def get_kalori(request):
    response={'output':'test'}
    output='test'
    age=request.GET.get('age',None)
    activity=request.GET.get('activity',None)
    gender=request.GET.get('gender',None)
    calorie=Calorie.objects.get(pk=1)
    calorie_value=calorie.total_calories
    low_limit=0
    high_limit=0
    if(gender=='Pria'):
        if(age=='Remaja'):
            if(activity=='Tidak Terlalu Aktif'):
                low_limit=2400
                high_limit=2400
            elif(activity=='Lumayan Aktif'):
                low_limit=2600
                high_limit=2800
            elif(activity=='Sangat Aktif'):
                low_limit=3000
                high_limit=3000
        elif(age=='Dewasa'):
            if(activity=='Tidak Terlalu Aktif'):
                low_limit=2200
                high_limit=2200
            elif(activity=='Lumayan Aktif'):
                low_limit=2400
                high_limit=2600
            elif(activity=='Sangat Aktif'):
                low_limit=2800
                high_limit=3000
        else:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
            if(activity=='Tidak Terlalu Aktif'):
                low_limit=2000
                high_limit=2000
            elif(activity=='Lumayan Aktif'):
                low_limit=2200
                high_limit=2400
            elif(activity=='Sangat Aktif'):
                low_limit=2400
                high_limit=2800
            
    else:
        if(age=='Remaja'):
            if(activity=='Tidak Terlalu Aktif'):
                low_limit=2000
                high_limit=2000
            elif(activity=='Lumayan Aktif'):
                low_limit=2000
                high_limit=2200
            elif(activity=='Sangat Aktif'):
                low_limit=2400
                high_limit=2400
        elif(age=='Dewasa'):
            if(activity=='Tidak Terlalu Aktif'):
                low_limit=1800
                high_limit=1800
            elif(activity=='Lumayan Aktif'):
                low_limit=2000
                high_limit=2000
            elif(activity=='Sangat Aktif'):
                low_limit=2200
                high_limit=2200
        else:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
            if(activity=='Tidak Terlalu Aktif'):
                low_limit=1600
                high_limit=1600
            elif(activity=='Lumayan Aktif'):
                low_limit=1800
                high_limit=1800
            elif(activity=='Sangat Aktif'):
                low_limit=2000
                high_limit=2200
    if(low_limit==0 or high_limit==0):
        output="Terjadi error dalam pemrosesan"
    if(calorie_value >= low_limit and calorie_value <=high_limit):
        output="Kalori Anda sudah terpenuhi"
    elif(calorie_value > high_limit):
        output="Makanan yang Anda pesan sudah melebihi {} dari batas kalori".format(calorie_value-high_limit)
    else:
        output="Makanan yang Anda pesan masih kurang {} dari batas kalori".format(low_limit-calorie_value)
    response={'output':output}
    return JsonResponse(response) 

kalori/templates/base_kalori.html
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load crispy_forms_tags %}
    {% load static %}
    <script src="{% static "jquery-3.4.1.js" %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href='{% static "kalori_new2.css" %}'>
</head>

kalori/templates/kalori.html
<!DOCTYPE html>
<html>
  {% load static %}
    {% load crispy_forms_tags %}
{% include 'base_kalori.html'%}
<body>
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
            <a class="navbar-brand" href="#">SiKantin</a>
            <ul class="navbar-nav mx-auto">
            <li class="nav-item">
                <a class="nav-link">Kalori</a>
            </li>
            </ul>
        </nav>
    </div>
     <br><br><br><br>
    <div class="d-flex justify-content-center">
        <h2>Yuk, Cek Kalori Makanan Pesanan Anda Di Sini!</h2>
    </div>
    <div class="container">
        <img class="bg_kalori" src="{% static 'Photos/Kalori.jpg' %}">
            <div class="form-group">
                {% csrf_token %}
                <div class="row mt-5">
                    <div class="col-12">
                        {{ form.age|as_crispy_field}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.gender|as_crispy_field}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.activity|as_crispy_field}}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <button  class="btn btn-outline-success" id="calorie-submit">Cek Kalori</button>
                </div>
                <div class="col-6">
                    <a class="btn btn-md btn-warning" href="/pemesanan/pembayaran/">Lanjut</a>
                </div>
            </div>
        </form>
    </div>
    <script type="text/javascript" src="{% static 'jquery-3.4.1.js' %}"></script>
    <script>
     $(document).on("click", "#calorie-submit", function(event){
                    event.preventDefault();
                    getResults();
        });
   
            function getResults() {
                var token = '{{csrf_token}}';
                var age=$("#id_age").val();
                var gender=$("#id_gender").val();
                var activity=$("#id_activity").val();
                $.ajax({
                    url:"{%url 'get_kalori'%}",
                    data:{
                        "headers": { "X-CSRFToken": token },
                        "age":age,
                        "gender":gender,
                        "activity":activity
                    },
                    datatype:"json",
                    success:function (result) {
                        alert(result.output);
                    }
                })
            }

    </script>
</body>
<br><br><br><br><br><br><br><br>
{% include 'footer.html'%}

kalori/templates/searchFood.html
{% load static %}
{% load crispy_forms_tags %}
{% include 'base_kalori.html'%}
 {% if user.is_authenticated %}
    {% include 'header2.html'%}
  {% else%}
    {% include 'header1.html'%}
  {% endif %}
   <style>
    
        label{
            font-family: "verdana";
        color:green;
        font-size:20px;
        }
    </style>
<body>
 <br><br><br><br><br><br>
 <div class="container-fluid">
            <div class="row justify-content-center text-center">
                <h2>Food Search Engine</h2>
            </div>
                    {% csrf_token %}
                    <div class="row justify-content-center">
                      <div class="col-12">
                        {{form.keyFood|as_crispy_field}}
                      </div>
                    </div>
                    <div class="row justify-content-center">
                      <div class="col-12">
                        {{form.keyCalorie|as_crispy_field}}
                      </div>
                    </div>

            <div class="row justify-content-center">
                <button class="btn btn-outline-success btn-lg" id="search-button">Search</button>
            </div>
</div>
    <div class="container-fluid">
        <div id="search-result">           
        </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'jquery-3.4.1.js' %}"></script>
    <script>
            $( document ).ready(function() {
               getResults(1);
          })
            $(document).on("click", "#search-button", function(event){
                    
                    event.preventDefault();
                    getResults(0);
                    
                });
            
             $(document).keypress(function(event) {
                var keycode = (event.keyCode ? event.keyCode : event.which);
                if(keycode == '13'){
                    event.preventDefault();
                    getResults(0); 
                }
            });
              function getResults(id) {
                var token = '{{csrf_token}}';
                if(id==0){
                  var query=$("#search1-query").val();
                  var cal=$("#search2-query").val();
                }
                else{
                  var query="sate";
                  var cal="0";
                }
                if(query==""){
                  query="null";
                }
                if(cal==""){
                  cal="0";
                }
                $.ajax({
                    url:"{%url 'get-food'%}",
                    data:{
                        "headers": { "X-CSRFToken": token },
                        "cal":cal,
                        "query":query
                    },
                    datatype:"json",
                    beforeSend: function(){
                        // Show image container
                        var content="<div class='text-center mb-5'><img src='{%static 'loading.gif'%}' alt='loading' width=350px></div>";
                        $("#search-result").html(content);
                    },
                    success:function (result) {    
                         $("#search-result").empty();          
                        var complete_text = ""
                        if(result.status=="failure"){
                          complete_text+='<div class="text-center mt-5 mb-5"><h3>Maaf terjadi error , coba gunakan layanan ini di lain waktu</h3></div>';
                        }
                        else{
                          if(result.results.length==0){
                              complete_text+='<div class="text-center mt-5 mb-5"><h3>Hasil tidak ditemukan :(</h3></div>';
                          }
                          else{
                              for (i = 0; i < result.results.length; i++) {
                                  var img =  result.results[i].image;
                                  var title =  result.results[i].title;
                                  if(img==null){
                                      img="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/romaine-lettuce-can-be-seen-at-a-store-in-mountain-view-news-photo-1575392907.jpg?resize=980:*";
                                  }
                                  complete_text +=
                              '<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 pt-3 pb-3">'+
                                      '<div class="hovereffect">'+
                                              '<img class="" src="' + img + '" alt="">'+
                                                  '<div class="overlay">'+
                                                      '<h2>' + title +'</h2>'+
                                                  '</div>'+                  
                                      '</div>'+
                                  '</div>';
                              }
                              
                          }
                        }
                        
                        $("#search-result").empty();
                        var container_open = '<div class="d-flex justify-content-around align-items-center flex-wrap">';
                        var container_close = '</div>';
                        $("#search-result").html(container_open+ complete_text + container_close);
                        
                    }
            })
        }
    </script>
</body>
<br><br><br><br><br><br>
{% include 'footer.html'%}